insert into public.councils (slug, name, portal_url, portal_type) values
  ('westminster',             'Westminster',              'https://idoxpa.westminster.gov.uk/online-applications',                                                         'idox_search_do'),
  ('camden',                  'Camden',                   'https://planningrecords.camden.gov.uk/Northgate/PlanningExplorer',                                              'idox_search_do'),
  ('islington',               'Islington',                'https://planning.islington.gov.uk/Northgate/PlanningExplorer',                                                  'idox_search_do'),
  ('hackney',                 'Hackney',                  'https://planning.hackney.gov.uk/online-applications',                                                           'idox_search_do'),
  ('tower-hamlets',           'Tower Hamlets',            'https://development.towerhamlets.gov.uk/online-applications',                                                   'idox_search_do'),
  ('southwark',               'Southwark',                'https://planning.southwark.gov.uk/online-applications',                                                         'idox_search_do'),
  ('lambeth',                 'Lambeth',                  'https://planning.lambeth.gov.uk/online-applications',                                                           'idox_search_do'),
  ('wandsworth',              'Wandsworth',               'https://planning.wandsworth.gov.uk/Northgate/PlanningExplorer',                                                  'idox_search_do'),
  ('kensington-and-chelsea',  'Kensington and Chelsea',   'https://www.rbkc.gov.uk/planning/searches/default.aspx',                                                        'idox_search_do'),
  ('hammersmith-and-fulham',  'Hammersmith and Fulham',   'https://public.lbhf.gov.uk/online-applications',                                                               'idox_search_do'),
  ('ealing',                  'Ealing',                   'https://pam.ealing.gov.uk/online-applications',                                                                 'idox_search_do'),
  ('brent',                   'Brent',                    'https://pa.brent.gov.uk/online-applications',                                                                   'idox_search_do'),
  ('haringey',                'Haringey',                 'https://www.planningservices.haringey.gov.uk/portal/servlets/ApplicationSearchServlet',                         'idox_servlet'),
  ('barnet',                  'Barnet',                   'https://barnet.planning-register.co.uk',                                                                        'idox_search_do'),
  ('enfield',                 'Enfield',                  'https://planningandbuildingcontrol.enfield.gov.uk/online-applications',                                         'idox_search_do'),
  ('waltham-forest',          'Waltham Forest',           'https://planning.walthamforest.gov.uk/online-applications',                                                     'idox_search_do'),
  ('newham',                  'Newham',                   'https://pa.newham.gov.uk/online-applications',                                                                  'idox_search_do'),
  ('greenwich',               'Greenwich',                'https://planning.royalgreenwich.gov.uk/online-applications',                                                    'idox_search_do'),
  ('lewisham',                'Lewisham',                 'https://planning.lewisham.gov.uk/online-applications',                                                          'idox_search_do'),
  ('bromley',                 'Bromley',                  'https://searchapplications.bromley.gov.uk/online-applications',                                                 'idox_search_do'),
  ('croydon',                 'Croydon',                  'https://publicaccess.croydon.gov.uk/online-applications',                                                       'idox_search_do'),
  ('merton',                  'Merton',                   'https://planning.merton.gov.uk/Northgate/PlanningExplorer',                                                     'idox_search_do'),
  ('kingston-upon-thames',    'Kingston upon Thames',     'https://publicaccess.kingston.gov.uk/online-applications',                                                      'idox_search_do'),
  ('richmond-upon-thames',    'Richmond upon Thames',     'https://www.richmond.gov.uk/council/how_we_work/richmond_online/planning_online',                               'idox_search_do'),
  ('bristol-city-of',         'Bristol',                  'https://pa.bristol.gov.uk/online-applications',                                                                 'idox_search_do'),
  ('leeds',                   'Leeds',                    'https://publicaccess.leeds.gov.uk/online-applications',                                                         'idox_search_do'),
  ('manchester',              'Manchester',               'https://pa.manchester.gov.uk/online-applications',                                                              'idox_search_do'),
  ('birmingham',              'Birmingham',               'https://eplanning.birmingham.gov.uk/Northgate/PlanningExplorer',                                                'idox_search_do'),
  ('sheffield',               'Sheffield',                'https://planningregister.sheffield.gov.uk',                                                                     'idox_search_do'),
  ('liverpool',               'Liverpool',                'https://planning.liverpool.gov.uk/online-applications',                                                         'idox_search_do'),
  ('staffordshire-moorlands', 'Staffordshire Moorlands',  'http://publicaccess.staffsmoorlands.gov.uk/portal/servlets/ApplicationSearchServlet',                          'idox_servlet')
on conflict (slug) do nothing;
